version: '3.9'

services:
  db:
    image: mysql:8
    command:  --default-authentication-plugin=mysql_native_password
    container_name: db
    restart: always
    tty: true
    volumes:
      - data:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=nodedb
      - MYSQL_ROOT_PASSWORD=root
    networks:
      - app-network

  app:
    entrypoint: dockerize -wait tcp://db:3306 -timeout 20s ./entrypoint.sh
    build:
      context: ./node
      dockerfile: Dockerfile
    container_name: node_service
    restart: always
    ports:
      - 8000:8000
    volumes:
      - ./node:/usr/app
      - /usr/app/node_modules
    depends_on:
      - db
    networks:
      - app-network
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"
  
  nginx:
    build:
      context: ./nginx
      dockerfile: ./docker/Dockerfile
    container_name: nginx
    ports:
      - "8080:80"
    networks:
      - app-network
    depends_on: 
      - app

volumes:
  data:

networks: 
  app-network:
    driver: bridge      